/**
 * Sidebar configuration file.
 *
 * Items can be:
 * - "autogenerated" — auto-scan a directory (default behavior)
 * - doc references with optional overrides
 * - external links
 * - category groupings
 *
 * If this file exports an empty object or the key for a section is not found,
 * the sidebar falls back to filesystem-based auto-generation.
 */

export interface SidebarLink {
  type: "link";
  label: string;
  href: string;
}

export interface SidebarDoc {
  type: "doc";
  id: string; // doc slug, e.g. "getting-started/introduction"
  label?: string; // override the doc's title in sidebar
}

export interface SidebarCategory {
  type: "category";
  label: string;
  items: SidebarItem[];
  collapsed?: boolean;
  sortOrder?: "asc" | "desc";
}

export interface SidebarAutogenerated {
  type: "autogenerated";
  dirName?: string; // subdirectory to scan (optional)
}

export type SidebarItem =
  | SidebarDoc
  | SidebarLink
  | SidebarCategory
  | SidebarAutogenerated
  | string;

// String shorthand: "getting-started/introduction" is equivalent to
// { type: "doc", id: "getting-started/introduction" }

export interface SidebarsConfig {
  [sectionKey: string]: SidebarItem[] | undefined;
}

/**
 * Sidebar configuration.
 * Keys correspond to headerNav categoryMatch values.
 * If a section has no config here, it uses auto-generated filesystem sidebar.
 */
const sidebars: SidebarsConfig = {
  methodology: [
    "methodology",
    {
      type: "category",
      label: "Architecture",
      items: [{ type: "autogenerated", dirName: "methodology/architecture" }],
    },
    {
      type: "category",
      label: "Design Systems",
      items: [
        { type: "autogenerated", dirName: "methodology/design-systems" },
      ],
    },
  ],
  layout: [
    "layout",
    {
      type: "category",
      label: "Flexbox & Grid",
      items: [{ type: "autogenerated", dirName: "layout/flexbox-and-grid" }],
    },
    {
      type: "category",
      label: "Positioning",
      items: [{ type: "autogenerated", dirName: "layout/positioning" }],
    },
    {
      type: "category",
      label: "Sizing",
      items: [{ type: "autogenerated", dirName: "layout/sizing" }],
    },
    {
      type: "category",
      label: "Specialized",
      items: [{ type: "autogenerated", dirName: "layout/specialized" }],
    },
  ],
  typography: [
    "typography",
    {
      type: "category",
      label: "Font Sizing",
      items: [{ type: "autogenerated", dirName: "typography/font-sizing" }],
    },
    {
      type: "category",
      label: "Text Control",
      items: [{ type: "autogenerated", dirName: "typography/text-control" }],
    },
    {
      type: "category",
      label: "Fonts",
      items: [{ type: "autogenerated", dirName: "typography/fonts" }],
    },
    {
      type: "category",
      label: "Text Effects",
      items: [{ type: "autogenerated", dirName: "typography/text-effects" }],
    },
  ],
  styling: [
    "styling",
    {
      type: "category",
      label: "Color",
      items: [{ type: "autogenerated", dirName: "styling/color" }],
    },
    {
      type: "category",
      label: "Shadows & Borders",
      items: [
        { type: "autogenerated", dirName: "styling/shadows-and-borders" },
      ],
    },
    {
      type: "category",
      label: "Effects",
      items: [{ type: "autogenerated", dirName: "styling/effects" }],
    },
  ],
  interactive: [
    "interactive",
    {
      type: "category",
      label: "States & Transitions",
      items: [
        {
          type: "autogenerated",
          dirName: "interactive/states-and-transitions",
        },
      ],
    },
    {
      type: "category",
      label: "Selectors",
      items: [{ type: "autogenerated", dirName: "interactive/selectors" }],
    },
    {
      type: "category",
      label: "Scroll",
      items: [{ type: "autogenerated", dirName: "interactive/scroll" }],
    },
    {
      type: "category",
      label: "Forms & Accessibility",
      items: [
        {
          type: "autogenerated",
          dirName: "interactive/forms-and-accessibility",
        },
      ],
    },
  ],
};

export default sidebars;
